# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Houssein Djirdeh
email: h.djirdeh@mail.utoronto.ca
description: > # this means to ignore newlines until "baseurl:"
  JavaScript, Angular and all things web 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://houssein.me/" # the base hostname & protocol for your site
linkedin_username: Houssein Djirdeh
github_username:  hdjirdeh
google_analytics: UA-66348622-2
gems:
  - jekyll-sitemap

# Build settings
markdown: kramdown